# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='dbsa',
    version='0.1.0',
    description='Dependency-Based Self-Attention for Transformer NMT (Deguchi et al., 2019)',
    python_requires='==3.*,>=3.6.0',
    author='Hiroyuki Deguchi',
    author_email='deguchi@ai.cs.ehime-u.ac.jp',
    license='MIT',
    packages=[
        'dbsa', 'dbsa.criterions', 'dbsa.data', 'dbsa.models', 'dbsa.modules',
        'dbsa.tasks'
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=['fairseq'],
    dependency_links=[
        'git+https://github.com/de9uch1/fairseq.git@return_self_attn#egg=fairseq'
    ],
)
