# @package _group_

hydra:
  run:
    dir: .

common:
    fp16: true

dataset:
    num_workers: 0
    max_tokens: 12000

optimization:
    max_update: 100000
    clip_norm: 0.0
    lr:
        - 7e-4

checkpoint:
    no_epoch_checkpoints: true
    write_checkpoints_asynchronously: false
    save_dir: checkpoints/
    save_interval_updates: 0
    keep_interval_updates: -1

model:
    _name: transformer_dep
    activation_fn: "relu"
    share_decoder_input_output_embed: true
    dropout: 0.1
    attention_dropout: 0.1
    activation_dropout: 0.1
    encoder:
        dependency_layer: 0
    decoder:
        dependency_layer: 0

task:
    _name: translation_dep
    load_dependency: true
    data: data-bin/

criterion:
    _name: label_smoothed_cross_entropy_with_dependency
    label_smoothing: 0.1
    source_dependency_lambda: 0.5
    target_dependency_lambda: 0.5

optimizer:
    _name: adam
    adam_betas:
        - 0.9
        - 0.98

lr_scheduler:
    _name: inverse_sqrt
    warmup_updates: 4000
    warmup_init_lr: 1e-7
